from anchor.ui.presenters.apps_presenter import AppsPresenter
from anchor.ui.presenters.git_stats_presenter import GitStatsPresenter
from anchor.ui.presenters.main_presenter import MainPresenter
from anchor.ui.presenters.ticket_content_presenter import TicketContentPresenter
from anchor.ui.presenters.ticket_state_presenter import TicketStatePresenter
from anchor.ui.presenters.tickets_list_presenter import TicketsListPresenter
from anchor.ui.presenters.feature_branch_presenter import FeatureBranchPresenter